CREATE TABLE [dbo].[Letter] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [CreateDate]            DATETIME        DEFAULT (getdate()) NOT NULL,
    [CreateUserId]          INT             DEFAULT ((1)) NOT NULL,
    [ModifyDate]            DATETIME        DEFAULT (getdate()) NOT NULL,
    [ModifyUserId]          INT             DEFAULT ((1)) NOT NULL,
    [IsActive]              BIT             DEFAULT ((1)) NOT NULL,
    [Number]                INT             NOT NULL,
    [PostCompanyId]         INT             NOT NULL,
    [Date]                  DATE            NOT NULL,
    [ReceiveDate]           DATE            NOT NULL,
    [Content]               NVARCHAR (150)  NULL,
    [EmployeeId]            INT             NULL,
    [CompanyId]             INT             NULL,
    [DocumentTypeId]        INT             NULL,
    [Other]                 NVARCHAR (150)  NULL,
    [PR]                    BIT             NULL,
    [PO]                    BIT             NULL,
    [CompanyName]           NVARCHAR (150)  NULL,
    [CompanyStreet]         NVARCHAR (150)  NULL,
    [CompanyCity]           NVARCHAR (150)  NULL,
    [CompanyPostalCode]     NVARCHAR (10)   NULL,
    [CompanyPostName]       NVARCHAR (150)  NULL,
    [CompanyPostStreet]     NVARCHAR (1500) NULL,
    [CompanyPostCity]       NVARCHAR (150)  NULL,
    [CompanyPostPostalCode] NVARCHAR (10)   NULL,
    [EmployeeFirstName]     NVARCHAR (150)  NULL,
    [EmployeeLastName]      NVARCHAR (150)  NULL,
    [Inbox]                 BIT             NULL,
    [Outbox]                BIT             NULL,
    CONSTRAINT [PK_Letter] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Letter_Company] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([Id]),
    CONSTRAINT [FK_Letter_CreateUser] FOREIGN KEY ([CreateUserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_Letter_DocumentType] FOREIGN KEY ([DocumentTypeId]) REFERENCES [dbo].[DocumentType] ([Id]),
    CONSTRAINT [FK_Letter_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([Id]),
    CONSTRAINT [FK_Letter_ModifyUser] FOREIGN KEY ([ModifyUserId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_Letter_PostCompanyId] FOREIGN KEY ([PostCompanyId]) REFERENCES [dbo].[PostCompany] ([Id])
);

